### PR TITLE
Type schema shape fix

### PR DESCRIPTION
**Pull request by seaingsky**
…mat info outside schema,  while still keeping the $ref type inside the schema, make it more swagger spec 2.0 compliant.

### CODE REVIEW

**Comment by dspeele** [comment]
Tests don't pass:
```
! Produce the main thing
[error]    JsonMatcherException: : In
[error] {
[error]   "swagger" : "2.0",
[error]   "produces" : [ "application/json" ],
[error]   "paths" : {
[error]     "/api/v1/users/{type}" : {
[error]       "get" : {
[error]         "summary" : "Get Users summary",
[error]         "description" : "Get Users description",
[error]         "parameters" : [ {
[error]           "in" : "path",
[error]           "name" : "type",
[error]           "description" : "",
[error]           "type" : "string",
[error]           "enum" : [ "man", "dog", "woman" ],
[error]           "required" : true
[error]         }, {
[error]           "in" : "query",
[error]           "name" : "age",
[error]           "description" : "",
[error]           "type" : "integer",
[error]           "format" : "int32",
[error]           "enum" : [ "2", "65", "9" ],
[error]           "required" : false
[error]         } ],
[error]         "tags" : [ "Users" ],
[error]         "responses" : {
[error]           "400" : {
[error]             "description" : "Something went wrong"
[error]           },
[error]           "200" : {
[error]             "description" : "An array of users",
[error]             "schema" : {
[error]               "type" : "array",
[error]               "items" : {
[error]                 "$ref" : "#/definitions/User"
[error]               }
[error]             }
[error]           }
[error]         }
[error]       },
[error]       "post" : {
[error]         "summary" : "Create User summary",
[error]         "description" : "Create User description",
[error]         "parameters" : [ {
[error]           "in" : "body",
[error]           "name" : "body",
[error]           "required" : true,
[error]           "description" : "",
[error]           "schema" : {
[error]             "$ref" : "#/definitions/User"
[error]           }
[error]         }, {
[error]           "in" : "path",
[error]           "name" : "type",
[error]           "required" : true,
[error]           "description" : "",
[error]           "type" : "string",
[error]           "enum" : [ "man", "dog", "woman" ]
[error]         } ],
[error]         "tags" : [ "Users" ],
[error]         "responses" : {
[error]           "400" : {
[error]             "description" : "Something went wrong"
[error]           },
[error]           "200" : {
[error]             "description" : "A User from post",
[error]             "schema" : {
[error]               "$ref" : "#/definitions/User"
[error]             }
[error]           }
[error]         }
[error]       }
[error]     },
[error]     "/api/v1/users2/{id}" : {
[error]       "get" : {
[error]         "summary" : "Get User summary",
[error]         "description" : "Get User description",
[error]         "parameters" : [ {
[error]           "name" : "id",
[error]           "required" : true,
[error]           "description" : "",
[error]           "schema" : {
[error]             "type" : "string"
[error]           },
[error]           "in" : "path",
[error]           "required" : true
[error]         } ],
[error]         "tags" : [ "Users2" ],
[error]         "responses" : {
[error]           "400" : {
[error]             "description" : "Something went wrong"
[error]           },
[error]           "200" : {
[error]             "description" : "A User from get",
[error]             "schema" : {
[error]               "type" : "string"
[error]             }
[error]           }
[error]         }
[error]       }
[error]     },
[error]     "/api/v1/cats" : {
[error]       "get" : {
[error]         "summary" : "Get Cats",
[error]         "description" : "Get Cats description",
[error]         "parameters" : [ ],
[error]         "tags" : [ "Cats" ],
[error]         "responses" : {
[error]           "200" : {
[error]             "description" : "Cats",
[error]             "schema" : {
[error]               "type" : "array",
[error]               "items" : {
[error]                 "type" : "string"
[error]               }
[error]             }
[error]           }
[error]         }
[error]       }
[error]     },
[error]     "/api/v1/dogs" : {
[error]       "get" : {
[error]         "summary" : "Get Dogs",
[error]         "description" : "Get Dogs description",
[error]         "parameters" : [ ],
[error]         "tags" : [ "Dogs" ],
[error]         "responses" : {
[error]           "200" : {
[error]             "description" : "Type",
[error]             "schema" : {
[error]               "type" : "string",
[error]               "enum" : [ "dog", "cat", "woman" ]
[error]             }
[error]           }
[error]         }
[error]       }
[error]     }
[error]   },
[error]   "definitions" : {
[error]     "User" : {
[error]       "id" : "User",
[error]       "required" : [ "id", "names", "age", "________ignoreOrder________" ],
[error]       "properties" : {
[error]         "id" : {
[error]           "type" : "integer",
[error]           "format" : "int64"
[error]         },
[error]         "id2" : {
[error]           "type" : "integer",
[error]           "format" : "int32"
[error]         },
[error]         "names" : {
[error]           "type" : "array",
[error]           "items" : {
[error]             "type" : "string"
[error]           }
[error]         },
[error]         "extra" : {
[error]           "$ref" : "#/definitions/Extra"
[error]         },
[error]         "type" : {
[error]           "type" : "string",
[error]           "enum" : [ "man", "woman", "dog" ]
[error]         },
[error]         "age" : {
[error]           "type" : "string",
[error]           "enum" : [ "2", "65", "9" ]
[error]         }
[error]       }
[error]     },
[error]     "Extra" : {
[error]       "id" : "Extra",
[error]       "required" : [ "extrastring" ],
[error]       "properties" : {
[error]         "extrastring" : {
[error]           "type" : "string",
[error]           "description" : "Extra type"
[error]         }
[error]       }
[error]     }
[error]   }
[error] }
[error] , the following fields are missing: info
[error]
[error] path:
[error]
[error]  *** Set JsonMatcher.verbose (or JsonMatcher.very_verbose) to true to get more details. ***
[error]
[error]   (JsonMatcher.scala:76)
[error] no.samordnaopptak.apidoc.JsonMatcher$.no$samordnaopptak$apidoc$JsonMatcher$$matchJsonFailed(JsonMatcher.scala:76)
[error] no.samordnaopptak.apidoc.JsonMatcher$.matchJsonObjects(JsonMatcher.scala:198)
[error] no.samordnaopptak.apidoc.JsonMatcher$.no$samordnaopptak$apidoc$JsonMatcher$$matchJson(JsonMatcher.scala:284)
[error] no.samordnaopptak.apidoc.JsonMatcher$.matchJson(JsonMatcher.scala:303)
[error] test.lib.SwaggerSpec$$anonfun$1$$anonfun$apply$2.apply$mcZ$sp(SwaggerSpec.scala:355)
```

**Comment by dspeele** [comment]
As we just discussed, I'm not sure we need the first part of the if statement which checks for enum. I also think this code block should really be lifted out and turned into its own function, possibly with a case statement. Finally, we should add a test for this change.

**Comment by seaingsky** [comment]
I would like to leave the part of checks for enum for now, as it is no harm. i am open to remove it if later we are comfortable and more versatile about swagger spec.  Tests are adjusted. please review and merge.

**Comment by dspeele** [comment]
Nice work, @seaingsky and @diamonddave!

**Pull request merged**
